# Generated by Django 4.2.7 on 2023-11-07 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_alter_orderproduct_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Shipped', 'Shipped'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
