# Generated by Django 4.2.4 on 2023-11-09 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_payment_amount_paid_alter_payment_payment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restock',
            field=models.BooleanField(default=False),
        ),
    ]
