# Generated by Django 4.2.7 on 2023-11-06 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name_plural': 'product galleries'},
        ),
    ]
