# Generated by Django 4.2.7 on 2023-11-08 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='image',
            new_name='images',
        ),
    ]
