# Generated by Django 4.2.4 on 2023-11-08 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_image_productgallery_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productgallery',
            old_name='images',
            new_name='image',
        ),
    ]
