# Generated by Django 4.2.4 on 2023-11-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_rename_images_productgallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
