# Generated by Django 4.2.4 on 2023-11-10 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_variation_is_featured'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='is_featured',
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
