# Generated by Django 5.1.4 on 2025-01-12 16:31

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_remove_category_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='cat_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
