# Generated by Django 4.2.4 on 2023-11-12 17:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0001_initial'),
        ('category', '0003_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='offers.categoryoffer'),
        ),
    ]
